language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - jruby
script: rake test

notifications:
  slack:
    secure: XubYKuE3+6VJNDvjgVE2P0cp3Km/We1RlhkeHBGI+r0wYqAg6tab33IYFo+3BgE0xwl1RX3SwX1pbPt3LVDi8zLA5mkmmmDiNIqqYa1vICDgRgu8OTCRcCCTaWB5DhVY11iZaYFyQEoQ+aUHp9QoYeH7Qmp+M2//+DYG9wka6kA=
