language: ruby

before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version
rvm: 
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
env:
  - JRUBY_OPTS=--1.8

script: rake test:unit

